''' dik.py - s3 starter dictionary '''

sdik = [
	#     s3             pos    parent            en               th
	('root'         ,'n'   ,None             ,'root'          ,'ราก'               ),
	('empty'        ,'j'   ,'root'           ,'empty'         ,'ว่าง'               ),
	('person'       ,'n'   ,'root'           ,'person'        ,'คน'                ),
	('place'        ,'n'   ,'root'           ,'place'         ,'สถานที่'             ),
	('thing'        ,'n'   ,'root'           ,'thing'         ,'สิ่ง'                ),
	('action'       ,'n'   ,'root'           ,'action'        ,'หนังบู๊'              ),
	('link'         ,'n'   ,'root'           ,'link'          ,'ลิงค์'               ),

	('typeof'       ,'p'   ,'link'           ,'typeof'        ,'ประเภทของ'         ),
	('of'           ,'p'   ,'link'           ,'ownedby'       ,'ของ'               ),
	('by'           ,'p'   ,'link'           ,'by'            ,'โดย'               ),

	('question'     ,'n'   ,'link'           ,'question'      ,'คำถาม'             ),
	('which'        ,'p'   ,'question'       ,'which'         ,'ที่'                 ),   # apply to noun
	('where'        ,'p'   ,'question'       ,'where'         ,'ที่ไหน'              ),   # apply to verb
	('why'          ,'p'   ,'question'       ,'why'           ,'ทำไม'              ),
	('when'         ,'p'   ,'question'       ,'when'          ,'เมื่อไหร่'            ),   # default "now"
	('how'          ,'p'   ,'question'       ,'how'           ,'อย่างไร'            ),
	('what'         ,'p'   ,'question'       ,'what'          ,'อะไร'              ),   # applies only to "do"

	('this'         ,'j'   ,'which'          ,'this'          ,'นี้'                 ),
	('next'         ,'j'   ,'which'          ,'next'          ,'ต่อไป'              ),
	('last'         ,'j'   ,'which'          ,'last'          ,'ล่าสุด'              ),   # previous

	('time_period'  ,'n'   ,'thing'          ,'time_period'   ,'ช่วงเวลา'           ),
	('week'         ,'n'   ,'time_period'    ,'week'          ,'สัปดาห์'             ),
	('day'          ,'n'   ,'time_period'    ,'day'           ,'วัน'                ),
	('month'        ,'n'   ,'time_period'    ,'month'         ,'เดือน'              ),
	('year'         ,'n'   ,'time_period'    ,'year'          ,'ปี'                 ),

	('time'         ,'n'   ,'thing'          ,'time'          ,'เวลา'              ),
	('now'          ,'a'   ,'time'           ,'now'           ,'ตอนนี้'              ),
	('yesterday'    ,'a'   ,'time'           ,'yesterday'     ,'เมื่อวานนี้'           ),
	('today'        ,'a'   ,'time'           ,'today'         ,'วันนี้'               ),
	('tomorrow'     ,'a'   ,'time'           ,'tomorrow'      ,'พรุ่งนี้'              ),
	('morning'      ,'a'   ,'time'           ,'morning'       ,'ตอนเช้า'            ),
	('afternoon'    ,'a'   ,'time'           ,'afternoon'     ,'ตอนบ่าย'            ),
	('evening'      ,'a'   ,'time'           ,'evening'       ,'ตอนเย็น'            ),

	('you'          ,'p'   ,'person'         ,'you'           ,'คุณ'                ),
	('I'            ,'p'   ,'person'         ,'I'             ,'ผม'                ),
	('friend'       ,'p'   ,'person'         ,'friend'        ,'เพื่อน'              ),
	('family'       ,'p'   ,'person'         ,'family'        ,'ครอบครัว'           ),
	('name'         ,'n'   ,'thing'          ,'name'          ,'ชี่อ'                ),
	('Nid'          ,'np'  ,'person'         ,'Nid'           ,'นิด'                ),
	('Pin'          ,'np'  ,'person'         ,'Pin'           ,'พิน'                ),
	('May'          ,'np'  ,'person'         ,'May'           ,'เมย์'               ),
	('Som'          ,'np'  ,'person'         ,'Som'           ,'ส้ม'                ),
	('Nui'          ,'np'  ,'person'         ,'Nui'           ,'นุ้ย'                ),
	('Memi'         ,'np'  ,'person'         ,'Memi'          ,'มีมี่'                ),
	('Fern'         ,'np'  ,'person'         ,'Fern'          ,'เฟร์น'              ),
	('Bella'        ,'np'  ,'person'         ,'Bella'         ,'เบลล่า'             ),
	('Jenny'        ,'np'  ,'person'         ,'Jenny'         ,'เจนนี่'              ),
	('Penny'        ,'np'  ,'person'         ,'Penny'         ,'เพนนี'              ),
	('Milky'        ,'np'  ,'person'         ,'Milky'         ,'มิ้ลกี้'               ),
	('Donut'        ,'np'  ,'person'         ,'Donut'         ,'โดนัท'              ),
	('Namtip'       ,'np'  ,'person'         ,'Namtip'        ,'น้ำทิพย์'             ),
	('Tangmo'       ,'np'  ,'person'         ,'Tangmo'        ,'แตงโม'             ),
	('Chompoo'      ,'np'  ,'person'         ,'Chompoo'       ,'ชมพู่'               ),
	('Naiyana'      ,'np'  ,'person'         ,'Naiyana'       ,'นัยนา'              ),
	('Sam'          ,'np'  ,'person'         ,'Sam'           ,'แซม'               ),
	('Joe'          ,'np'  ,'person'         ,'Joe'           ,'โจ'                ),
	('John'         ,'np'  ,'person'         ,'John'          ,'จน'                ),
	('Juan'         ,'np'  ,'person'         ,'Juan'          ,'ฆ'                 ),

	('city'          ,'n'  ,'place'          ,'city'          ,'เมือง'              ),
	('island'        ,'n'  ,'place'          ,'island'        ,'เกาะ'              ),
	('house'         ,'n'  ,'place'          ,'house'         ,'บ้าน'               ),

	('businesstype'  ,'n'  ,'thing'          ,'businesstype'  ,'ประเภทธุรกิจ'        ),
	('bank'          ,'n'  ,'businesstype'   ,'bank'          ,'ธนาคาร'            ),
	('coffeeshop'    ,'n'  ,'businesstype'   ,'coffeeshop'    ,'ร้านกาแฟ'           ),
	('restaurant'    ,'n'  ,'businesstype'   ,'restaurant'    ,'ร้านอาหาร'          ),
	('salon'         ,'n'  ,'businesstype'   ,'salon'         ,'ร้านเสริมสวย'        ),
	('market'        ,'n'  ,'businesstype'   ,'market'        ,'ตลาด'              ),
	('mall'          ,'n'  ,'businesstype'   ,'mall'          ,'ห้างสรรพสินค้า'       ),
	('pharmacy'      ,'n'  ,'businesstype'   ,'pharmacy'      ,'ร้านขายยา'          ),
	('cinema'        ,'n'  ,'businesstype'   ,'cinema'        ,'โรงภาพยนตร์'        ),
	('doctor'        ,'n'  ,'businesstype'   ,'doctor'        ,'หมอ'               ),
	('hospital'      ,'n'  ,'businesstype'   ,'hospital'      ,'โรงพยาบาล'         ),
	('clinic'        ,'n'  ,'businesstype'   ,'clinic'        ,'คลินิก'              ),
	('dentist'       ,'n'  ,'businesstype'   ,'dentist'       ,'ทันตแพทย์'           ),
	('embassy'       ,'n'  ,'businesstype'   ,'embassy'       ,'สถานทูต'            ),

	('Bangkok'       ,'np' ,'city'           ,'Bangkok'       ,'กรุงเทพมหานคร'      ),
	('Phuket'        ,'np' ,'city'           ,'Phuket'        ,'ภูเก็ต'              ),
	('Koh_Samui'     ,'np' ,'island'         ,'Koh_Samui'     ,'เกาะสมุย'           ),
	('Krabi'         ,'np' ,'city'           ,'Krabi'         ,'กระบี่'              ),
	('Pattaya'       ,'np' ,'city'           ,'Pattaya'       ,'พัทยา'              ),
	('Hua_Hin'       ,'np' ,'city'           ,'Hua_Hin'       ,'หัวหิน'              ),
	('Chiang_Mai'    ,'np' ,'city'           ,'Chiang_Mai'    ,'เชียงใหม่'           ),
	('Pai'           ,'np' ,'city'           ,'Pai'           ,'ปาย'               ),
	('Udon_Thani'    ,'np' ,'city'           ,'Udon_Thani'    ,'อุดรธานี'            ),
	('Sukothai'      ,'np' ,'city'           ,'Sukothai'      ,'สุโขทัย'             ),
	('Ayutthaya'     ,'np' ,'city'           ,'Ayutthaya'     ,'อยุธยา'             ),

	('food'          ,'n'  ,'thing'          ,'food'          ,'อาหาร'             ),
	('vacation'      ,'n'  ,'thing'          ,'vacation'      ,'วันหยุดพักผ่อน'        ),
	('business'      ,'n'  ,'thing'          ,'business'      ,'ธุรกิจ'              ),
	('money'         ,'n'  ,'thing'          ,'money'         ,'เงิน'               ),
	('coffee'        ,'n'  ,'food'           ,'coffee'        ,'กาแฟ'              ),
	('breakfast'     ,'n'  ,'food'           ,'breakfast'     ,'อาหารเช้า'          ),
	('hair'          ,'n'  ,'thing'          ,'hair'          ,'ผม'                ),
	('pedicure'      ,'n'  ,'thing'          ,'pedicure'      ,'เล็บเท้า'            ),
	('manicure'      ,'n'  ,'thing'          ,'manicure'      ,'ทำเล็บ'             ),
	('medicine'      ,'n'  ,'thing'          ,'medicine'      ,'ยา'                ),
	('movie'         ,'n'  ,'thing'          ,'movie'         ,'ภาพยนตร์'           ),
	('checkup'       ,'n'  ,'thing'          ,'checkup'       ,'ตรวจสอบ'           ),
	('headache'      ,'n'  ,'thing'          ,'headache'      ,'ปวดหัว'             ),
	('covid'         ,'n'  ,'thing'          ,'covid'         ,'โควิด'              ),
	('tooth'         ,'n'  ,'thing'          ,'tooth'         ,'ฟัน'                ),
	('teeth'         ,'n'  ,'thing'          ,'teeth'         ,'ฟัน'                ),
	('filling'       ,'n'  ,'thing'          ,'filling'       ,'การกรอก'           ),
	('whitening'     ,'n'  ,'thing'          ,'whitening'     ,'ไวท์เทนนิ่ง'          ),
	('toothache'     ,'n'  ,'thing'          ,'toothache'     ,'ปวดฟัน'             ),
	('braces'        ,'n'  ,'thing'          ,'braces'        ,'จัดฟัน'              ),
	('fun'           ,'n'  ,'thing'          ,'fun'           ,'สนุก'               ),

	('transport'     ,'n'  ,'thing'          ,'transport'     ,'ขนส่ง'              ),
	('train'         ,'n'  ,'transport'      ,'train'         ,'รถไฟ'              ),
	('bus'           ,'n'  ,'transport'      ,'bus'           ,'รถบัส'              ),
	('airplane'      ,'n'  ,'transport'      ,'airplane'      ,'เครื่องบิน'           ),
	('ship'          ,'n'  ,'transport'      ,'ship'          ,'เรือ'               ),

	('Grab'          ,'np' ,'transport'      ,'Grab'          ,'คว้า'               ),
	('car'           ,'n'  ,'transport'      ,'car'           ,'รถยนต์'             ),
	('taxi'          ,'n'  ,'transport'      ,'taxi'          ,'แท็กซี่'              ),
	('citybus'       ,'n'  ,'transport'      ,'citybus'       ,'ซิตี้บัส'              ),
	('songtaew'      ,'n'  ,'transport'      ,'songtaew'      ,'สองแถว'            ),
	('tuktuk'        ,'n'  ,'transport'      ,'tuktuk'        ,'ตุ๊กตุ๊ก'              ),

	('walk'          ,'v'  ,'action'         ,'walk'          ,'เดิน'               ),
	('run'           ,'v'  ,'action'         ,'run'           ,'วิ่ง'                ),

	('do'            ,'v'  ,'action'         ,'do'            ,'ทำ'                ),
	('go'            ,'v'  ,'action'         ,'go'            ,'ไป'                ),
	('come'          ,'v'  ,'action'         ,'come'          ,'มา'                ),
	('eat'           ,'v'  ,'action'         ,'eat'           ,'กิน'                ),
	('visit'         ,'v'  ,'action'         ,'visit'         ,'เยี่ยมชม'            ),
	('pickup'        ,'v'  ,'action'         ,'pickup'        ,'ไปรับ'              ),
	('deliver'       ,'v'  ,'action'         ,'deliver'       ,'ส่งมอบ'             ),
	('get'           ,'v'  ,'action'         ,'get'           ,'ได้รับ'              ),
	('drink'         ,'v'  ,'action'         ,'drink'         ,'ดื่ม'                ),
	('meet'          ,'v'  ,'action'         ,'meet'          ,'พบกัน'              ),
	('wash'          ,'v'  ,'action'         ,'wash'          ,'ล้าง'               ),
	('cut'           ,'v'  ,'action'         ,'cut'           ,'ตัด'                ),
	('buy'           ,'v'  ,'action'         ,'buy'           ,'ซื้อ'                ),
	('shop'          ,'v'  ,'action'         ,'shop'          ,'ร้านค้า'             ),
	('watch'         ,'v'  ,'action'         ,'watch'         ,'ดู'                 ),
	('fix'           ,'v'  ,'action'         ,'fix'           ,'แก้ไข'              ),
	('test'          ,'v'  ,'action'         ,'test'          ,'ทดสอบ'             ),
	('see'           ,'v'  ,'action'         ,'see'           ,'ดู'                 ),
	('clean'         ,'v'  ,'action'         ,'clean'         ,'สะอาด'             ),
	('remove'        ,'v'  ,'action'         ,'remove'        ,'ลบ'                ),

	('cook'          ,'v'  ,'action'         ,'cook'          ,'ปรุงอาหาร'          ),
	('brew'          ,'v'  ,'action'         ,'brew'          ,'ชง'                ),
	('read'          ,'v'  ,'action'         ,'read'          ,'อ่าน'               ),
	('listen'        ,'v'  ,'action'         ,'listen'        ,'ฟัง'                ),
	('play'          ,'v'  ,'action'         ,'play'          ,'เล่น'               ),
	('is'            ,'v'  ,'action'         ,'is'            ,'คือ'                ),
	('feel'          ,'v'  ,'action'         ,'feel'          ,'รู้สึก'               ),

	('relax'         ,'v'  ,'action'         ,'relax'         ,'ผ่อนคลาย'           ),
	('chat'          ,'v'  ,'action'         ,'chat'          ,'แชท'               ),
	('talk'          ,'v'  ,'action'         ,'talk'          ,'พูด'                ),
	('give'          ,'v'  ,'action'         ,'give'          ,'ให้'                ),

	('with'          ,'p'  ,'link'           ,'with'          ,'กับ'                ),

	('have'          ,'v'  ,'action'         ,'have'          ,'มี'                 ),
	('study'         ,'v'  ,'action'         ,'study'         ,'ศึกษา'              ),
	('work'          ,'v'  ,'action'         ,'work'          ,'งาน'               ),

	('animal'        ,'n'  ,'root'           ,'animal'        ,'สัตว์'               ),
	('cow'           ,'n'  ,'animal'         ,'cow'           ,'วัว'                ),

	('foodtype'      ,'n'  ,'root'           ,'foodtype'      ,'ประเภทอาหาร'       ),
	('rice'          ,'n'  ,'foodtype'       ,'rice'          ,'ข้าว'               ),
	('tea'           ,'n'  ,'foodtype'       ,'tea'           ,'ชา'                ),

	('book'          ,'n'  ,'thing'          ,'book'          ,'หนังสือ'             ),
	('music'         ,'n'  ,'thing'          ,'music'         ,'เพลง'              ),
	('game'          ,'n'  ,'thing'          ,'game'          ,'เกม'               ),
	('homework'      ,'n'  ,'thing'          ,'homework'      ,'การบ้าน'            ),
	('assignment'    ,'n'  ,'thing'          ,'assignment'    ,'การมอบหมาย'        ),
	('computer'      ,'n'  ,'thing'          ,'computer'      ,'คอมพิวเตอร์'         ),
	('job'           ,'n'  ,'thing'          ,'job'           ,'งาน'               ),
	('garden'        ,'n'  ,'thing'          ,'garden'        ,'สวน'               ),
	('weed'          ,'n'  ,'thing'          ,'weed'          ,'วัชพืช'              ),
	('harvest'       ,'n'  ,'thing'          ,'harvest'       ,'เก็บเกี่ยว'           ),
	('plant'         ,'n'  ,'thing'          ,'plant'         ,'ปลูก'               ),

	('due'           ,'j'  ,'thing'          ,'due'           ,'ครบกำหนด'          ),   # state, adj
	('many'          ,'a'  ,'thing'          ,'many'          ,'มากมาย'            ),   # adv
	('howmuch'       ,'a'  ,'link'           ,'howmuch'       ,'เท่าไหร่'            ),   # adv
	('too'           ,'a'  ,'howmuch'        ,'too'           ,'เกิน'               ),

	('feeling'       ,'n'  ,'root'           ,'feeling'       ,'ความรู้สึก'           ),
	('hungry'        ,'n'  ,'feeling'        ,'hungry'        ,'หิว'                ),

	('kitchen'       ,'n'  ,'place'          ,'kitchen'       ,'ครัว'               ),
	('backyard'      ,'n'  ,'place'          ,'backyard'      ,'สนามหลังบ้าน'        ),
	('upstairs'      ,'n'  ,'place'          ,'upstairs'      ,'ชั้นบน'              ),
	('bedroom'       ,'n'  ,'place'          ,'bedroom'       ,'ห้องนอน'            ),
	('livingroom'    ,'n'  ,'place'          ,'livingroom'    ,'ห้องนั่งเล่น'          ),

	('online'        ,'a'  ,'place'          ,'online'        ,'ออน'               ),

	('command'       ,'n'  ,'root'           ,'command'       ,'คำสั่ง'              ),
	('connect'       ,'v'  ,'command'        ,'connect'       ,'โยงใย'             ),
	('password'      ,'n'  ,'thing'          ,'password'      ,'รหัสผ่าน'            ),
	('translate'     ,'v'  ,'command'        ,'translate'     ,'แปล'               ),
	('echo'          ,'v'  ,'command'        ,'echo'          ,'เลียน'              ),
	('show'          ,'v'  ,'command'        ,'show'          ,'แสดง'              ),
	('search'        ,'v'  ,'command'        ,'search'        ,'ค้นหา'              ),
	('drill'         ,'v'  ,'command'        ,'drill'         ,'ฝึก'                ),
]
